<?php
/**
 * Converts beapi/key-figure content to blockparty/key-figure.
 *
 * @package Blockparty\Key_Figure
 */

namespace Blockparty\Key_Figure\Migration;

/**
 * Turns legacy beapi/key-figure markup into blockparty/key-figure markup.
 *
 * @psalm-suppress MixedArgument
 * @psalm-suppress MixedAssignment
 * @psalm-suppress MixedArrayAccess
 * @psalm-suppress MixedArrayAssignment
 * @psalm-suppress MixedArgumentTypeCoercion
 */
class KeyFigureBlockMigrator {

	/**
	 * Block name used by the legacy beapi/key-figure-block plugin.
	 *
	 * @var string
	 */
	const LEGACY_BLOCK_NAME = 'beapi/key-figure';

	/**
	 * Block name used by this plugin.
	 *
	 * @var string
	 */
	const BLOCK_NAME = 'blockparty/key-figure';

	/**
	 * BEM root class generated by the legacy block name.
	 *
	 * @var string
	 */
	const LEGACY_CLASS_ROOT = 'wp-block-beapi-key-figure';

	/**
	 * BEM root class generated by the current block name.
	 *
	 * @var string
	 */
	const CLASS_ROOT = 'wp-block-blockparty-key-figure';

	/**
	 * How many blocks were renamed.
	 *
	 * @var int
	 */
	public int $renamed = 0;

	/**
	 * How many blocks had their markup aligned with the current block output.
	 *
	 * @var int
	 */
	public int $modernized = 0;

	/**
	 * How many blocks were renamed but could not be modernized.
	 *
	 * @var int
	 */
	public int $skipped = 0;

	/**
	 * Check whether a content string holds legacy key figure markup.
	 *
	 * @param string $content Post content, widget content or option value.
	 * @return bool
	 */
	public function needs_migration( string $content ): bool {
		return false !== strpos( $content, 'wp:' . self::LEGACY_BLOCK_NAME )
			|| false !== strpos( $content, self::LEGACY_CLASS_ROOT );
	}

	/**
	 * Rewrite a content string, or return null when there is nothing to do.
	 *
	 * @param string $content   Post content, widget content or option value.
	 * @param bool   $modernize Whether to align the markup with the current block output.
	 * @return string|null
	 */
	public function migrate_content( string $content, bool $modernize = true ): ?string {
		if ( ! $this->needs_migration( $content ) ) {
			return null;
		}

		/** @psalm-suppress MixedArgumentTypeCoercion */
		$migrated = serialize_blocks( $this->migrate_blocks( parse_blocks( $content ), $modernize ) );

		// Legacy classes also live outside of key figure blocks (core/html,
		// classic content, theme markup), where only a rename is possible.
		$migrated = $this->rename_markup( $migrated );

		return $migrated === $content ? null : $migrated;
	}

	/**
	 * Walk every block and convert the legacy ones.
	 *
	 * @param array $blocks    Parsed blocks.
	 * @param bool  $modernize Whether to align the markup with the current block output.
	 * @return array
	 */
	private function migrate_blocks( array $blocks, bool $modernize ): array {
		foreach ( $blocks as $index => $block ) {
			if ( self::LEGACY_BLOCK_NAME === ( $block['blockName'] ?? '' ) ) {
				$blocks[ $index ] = $this->convert_block( $block, $modernize );
				continue;
			}

			if ( is_array( $block['innerBlocks'] ?? null ) && [] !== $block['innerBlocks'] ) {
				/** @var array $inner_blocks */
				$inner_blocks         = $block['innerBlocks'];
				$block['innerBlocks'] = $this->migrate_blocks( $inner_blocks, $modernize );
				$blocks[ $index ]     = $block;
			}
		}

		return $blocks;
	}

	/**
	 * Convert a single legacy block.
	 *
	 * @param array $block     Legacy block.
	 * @param bool  $modernize Whether to align the markup with the current block output.
	 * @return array
	 */
	private function convert_block( array $block, bool $modernize ): array {
		$attrs        = is_array( $block['attrs'] ?? null ) ? (array) $block['attrs'] : [];
		$inner_html   = $this->rename_markup( (string) ( $block['innerHTML'] ?? '' ) );
		$inner_blocks = is_array( $block['innerBlocks'] ?? null ) ? (array) $block['innerBlocks'] : [];

		/** @var array<int, string|null> $chunks */
		$chunks        = is_array( $block['innerContent'] ?? null ) ? (array) $block['innerContent'] : [ $inner_html ];
		$inner_content = [];

		foreach ( $chunks as $chunk ) {
			$inner_content[] = is_string( $chunk ) ? $this->rename_markup( $chunk ) : $chunk;
		}

		$block['blockName']    = self::BLOCK_NAME;
		$block['innerHTML']    = $inner_html;
		$block['innerContent'] = $inner_content;

		++$this->renamed;

		if ( ! $modernize || [] !== $inner_blocks ) {
			return $block;
		}

		$modernized = $this->modernize_markup( $inner_html, $attrs );

		if ( null === $modernized ) {
			++$this->skipped;

			return $block;
		}

		// Both values are read from the markup by the current block.
		unset( $attrs['decimalSeparator'], $attrs['minimumFractionDigits'] );

		$block['attrs']        = $attrs;
		$block['innerHTML']    = $modernized;
		$block['innerContent'] = [ $modernized ];

		++$this->modernized;

		return $block;
	}

	/**
	 * Replace the legacy block name and BEM root class.
	 *
	 * @param string $markup Block delimiters and/or HTML.
	 * @return string
	 */
	private function rename_markup( string $markup ): string {
		$markup = (string) preg_replace(
			'#(<!--\s*/?\s*)wp:' . preg_quote( self::LEGACY_BLOCK_NAME, '#' ) . '(?![\w/-])#',
			'${1}wp:' . self::BLOCK_NAME,
			$markup
		);

		return str_replace( self::LEGACY_CLASS_ROOT, self::CLASS_ROOT, $markup );
	}

	/**
	 * Align renamed markup with the output of the current block.
	 *
	 * The legacy block stored the decimal options as block attributes and the
	 * number already formatted, while the current block stores the options as
	 * data attributes and formats the raw number on the front end.
	 *
	 * @param string $markup Renamed block markup.
	 * @param array  $attrs  Legacy block attributes.
	 * @return string|null Null when the number cannot be read from the markup.
	 */
	private function modernize_markup( string $markup, array $attrs ): ?string {
		$number_pattern = sprintf(
			'#<span((?:[^>]*\s)?class="[^"]*%s__number[^"]*"[^>]*)>(.*?)</span>#s',
			preg_quote( self::CLASS_ROOT, '#' )
		);

		if ( ! preg_match( $number_pattern, $markup, $number ) ) {
			return null;
		}

		if ( ! preg_match( '#\sdata-increment="([^"]*)"#', $number[1], $increment ) || '' === $increment[1] ) {
			return null;
		}

		$number_attributes = $number[1];

		if ( false === strpos( $number_attributes, 'data-decimal-separator' ) ) {
			$number_attributes .= sprintf(
				' data-decimal-separator="%s"',
				esc_attr( (string) ( $attrs['decimalSeparator'] ?? 'none' ) )
			);
		}

		if ( false === strpos( $number_attributes, 'data-minimum-fraction-digits' ) ) {
			$number_attributes .= sprintf(
				' data-minimum-fraction-digits="%s"',
				esc_attr( (string) ( $attrs['minimumFractionDigits'] ?? '3' ) )
			);
		}

		$markup = str_replace(
			$number[0],
			sprintf( '<span%1$s>%2$s</span>', $number_attributes, esc_html( $increment[1] ) ),
			$markup
		);

		return $this->ensure_description( $this->convert_key_wrapper( $markup ) );
	}

	/**
	 * Add the description paragraph that the current block always saves.
	 *
	 * @param string $markup Renamed block markup.
	 * @return string
	 */
	private function ensure_description( string $markup ): string {
		if ( false !== strpos( $markup, self::CLASS_ROOT . '__description' ) ) {
			return $markup;
		}

		$paragraph = sprintf( '<p class="%s__description"></p>', self::CLASS_ROOT );
		$wrapper   = strrpos( $markup, '</div>' );

		if ( false === $wrapper ) {
			return $markup . $paragraph;
		}

		return substr_replace( $markup, $paragraph, $wrapper, 0 );
	}

	/**
	 * Turn the legacy `div` key wrapper into the `p` wrapper used since 1.1.0.
	 *
	 * @param string $markup Renamed block markup.
	 * @return string
	 */
	private function convert_key_wrapper( string $markup ): string {
		$pattern = sprintf(
			'#<div((?:[^>]*\s)?class="[^"]*%s__key[^"]*"[^>]*)>((?:(?!<div)[\s\S])*?)</div>#',
			preg_quote( self::CLASS_ROOT, '#' )
		);

		return (string) preg_replace( $pattern, '<p${1}>${2}</p>', $markup );
	}
}
